//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableHockeyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableHockeyPlayer
    {
        public TableHockeyPlayer()
        {
            this.TableHockeyGame = new HashSet<TableHockeyGame>();
            this.TableHockeyGame1 = new HashSet<TableHockeyGame>();
            this.TableHockeyContestPlayers = new HashSet<TableHockeyContestPlayer>();
            this.TableHockeyGames2 = new HashSet<TableHockeyGame>();
        }
    
        public int PlayerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ClubId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public byte[] PlayerBinary { get; set; }
        public Nullable<System.Guid> RegisteredByUserId { get; set; }
        public int isHistoric { get; set; }
    
        public virtual ICollection<TableHockeyGame> TableHockeyGame { get; set; }
        public virtual ICollection<TableHockeyGame> TableHockeyGame1 { get; set; }
        public virtual ICollection<TableHockeyContestPlayer> TableHockeyContestPlayers { get; set; }
        public virtual ICollection<TableHockeyGame> TableHockeyGames2 { get; set; }
    }
}
