//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableHockeyData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UHSSWEB_DEVEntities : DbContext
    {
        public UHSSWEB_DEVEntities()
            : base("name=UHSSWEB_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TableHockeyGame> TableHockeyGame { get; set; }
        public DbSet<TableHockeyPlayer> TableHockeyPlayer { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<TableHockeyContestPlayer> TableHockeyContestPlayers { get; set; }
        public DbSet<TableHockeyContestRound> TableHockeyContestRounds { get; set; }
        public DbSet<TableHockeyClub> TableHockeyClubs { get; set; }
        public DbSet<TableHockeyContest> TableHockeyContests { get; set; }
    }
}
