//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableHockeyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableHockeyContestRound
    {
        public TableHockeyContestRound()
        {
            this.TableHockeyGame = new HashSet<TableHockeyGame>();
        }
    
        public int TableHockeyContestRoundId { get; set; }
        public int ContestId { get; set; }
        public int RoundNumber { get; set; }
        public bool isFirstRound { get; set; }
        public bool isFinalRound { get; set; }
        public Nullable<bool> isEndGameRound { get; set; }
    
        public virtual TableHockeyContest TableHockeyContest { get; set; }
        public virtual ICollection<TableHockeyGame> TableHockeyGame { get; set; }
    }
}
