//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("UHSSWEB_DEVModel", "FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyClub", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableHockeyDAL.TableHockeyClub), "TableHockeyPlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableHockeyDAL.TableHockeyPlayer), true)]
[assembly: EdmRelationshipAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyContest", "TableHockeyContest", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableHockeyDAL.TableHockeyContest), "TableHockeyGame", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableHockeyDAL.TableHockeyGame), true)]
[assembly: EdmRelationshipAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyPlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableHockeyDAL.TableHockeyPlayer), "TableHockeyGame", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableHockeyDAL.TableHockeyGame), true)]
[assembly: EdmRelationshipAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyPlayer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableHockeyDAL.TableHockeyPlayer), "TableHockeyGame", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableHockeyDAL.TableHockeyGame), true)]

#endregion

namespace TableHockeyDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UHSSWEB_DEVEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UHSSWEB_DEVEntities object using the connection string found in the 'UHSSWEB_DEVEntities' section of the application configuration file.
        /// </summary>
        public UHSSWEB_DEVEntities() : base("name=UHSSWEB_DEVEntities", "UHSSWEB_DEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UHSSWEB_DEVEntities object.
        /// </summary>
        public UHSSWEB_DEVEntities(string connectionString) : base(connectionString, "UHSSWEB_DEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UHSSWEB_DEVEntities object.
        /// </summary>
        public UHSSWEB_DEVEntities(EntityConnection connection) : base(connection, "UHSSWEB_DEVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TableHockeyClub> TableHockeyClub
        {
            get
            {
                if ((_TableHockeyClub == null))
                {
                    _TableHockeyClub = base.CreateObjectSet<TableHockeyClub>("TableHockeyClub");
                }
                return _TableHockeyClub;
            }
        }
        private ObjectSet<TableHockeyClub> _TableHockeyClub;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TableHockeyContest> TableHockeyContest
        {
            get
            {
                if ((_TableHockeyContest == null))
                {
                    _TableHockeyContest = base.CreateObjectSet<TableHockeyContest>("TableHockeyContest");
                }
                return _TableHockeyContest;
            }
        }
        private ObjectSet<TableHockeyContest> _TableHockeyContest;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TableHockeyGame> TableHockeyGame
        {
            get
            {
                if ((_TableHockeyGame == null))
                {
                    _TableHockeyGame = base.CreateObjectSet<TableHockeyGame>("TableHockeyGame");
                }
                return _TableHockeyGame;
            }
        }
        private ObjectSet<TableHockeyGame> _TableHockeyGame;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TableHockeyPlayer> TableHockeyPlayer
        {
            get
            {
                if ((_TableHockeyPlayer == null))
                {
                    _TableHockeyPlayer = base.CreateObjectSet<TableHockeyPlayer>("TableHockeyPlayer");
                }
                return _TableHockeyPlayer;
            }
        }
        private ObjectSet<TableHockeyPlayer> _TableHockeyPlayer;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TableHockeyClub EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTableHockeyClub(TableHockeyClub tableHockeyClub)
        {
            base.AddObject("TableHockeyClub", tableHockeyClub);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TableHockeyContest EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTableHockeyContest(TableHockeyContest tableHockeyContest)
        {
            base.AddObject("TableHockeyContest", tableHockeyContest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TableHockeyGame EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTableHockeyGame(TableHockeyGame tableHockeyGame)
        {
            base.AddObject("TableHockeyGame", tableHockeyGame);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TableHockeyPlayer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTableHockeyPlayer(TableHockeyPlayer tableHockeyPlayer)
        {
            base.AddObject("TableHockeyPlayer", tableHockeyPlayer);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UHSSWEB_DEVModel", Name="TableHockeyClub")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableHockeyClub : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TableHockeyClub object.
        /// </summary>
        /// <param name="clubId">Initial value of the ClubId property.</param>
        /// <param name="foundedDate">Initial value of the FoundedDate property.</param>
        public static TableHockeyClub CreateTableHockeyClub(global::System.Int32 clubId, global::System.DateTime foundedDate)
        {
            TableHockeyClub tableHockeyClub = new TableHockeyClub();
            tableHockeyClub.ClubId = clubId;
            tableHockeyClub.FoundedDate = foundedDate;
            return tableHockeyClub;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClubId
        {
            get
            {
                return _ClubId;
            }
            set
            {
                if (_ClubId != value)
                {
                    OnClubIdChanging(value);
                    ReportPropertyChanging("ClubId");
                    _ClubId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClubId");
                    OnClubIdChanged();
                }
            }
        }
        private global::System.Int32 _ClubId;
        partial void OnClubIdChanging(global::System.Int32 value);
        partial void OnClubIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClubName
        {
            get
            {
                return _ClubName;
            }
            set
            {
                OnClubNameChanging(value);
                ReportPropertyChanging("ClubName");
                _ClubName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClubName");
                OnClubNameChanged();
            }
        }
        private global::System.String _ClubName;
        partial void OnClubNameChanging(global::System.String value);
        partial void OnClubNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClubPhoneNo
        {
            get
            {
                return _ClubPhoneNo;
            }
            set
            {
                OnClubPhoneNoChanging(value);
                ReportPropertyChanging("ClubPhoneNo");
                _ClubPhoneNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClubPhoneNo");
                OnClubPhoneNoChanged();
            }
        }
        private global::System.String _ClubPhoneNo;
        partial void OnClubPhoneNoChanging(global::System.String value);
        partial void OnClubPhoneNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FoundedDate
        {
            get
            {
                return _FoundedDate;
            }
            set
            {
                OnFoundedDateChanging(value);
                ReportPropertyChanging("FoundedDate");
                _FoundedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FoundedDate");
                OnFoundedDateChanged();
            }
        }
        private global::System.DateTime _FoundedDate;
        partial void OnFoundedDateChanging(global::System.DateTime value);
        partial void OnFoundedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DefunctDate
        {
            get
            {
                return _DefunctDate;
            }
            set
            {
                OnDefunctDateChanging(value);
                ReportPropertyChanging("DefunctDate");
                _DefunctDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefunctDate");
                OnDefunctDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DefunctDate;
        partial void OnDefunctDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDefunctDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClubLocation
        {
            get
            {
                return _ClubLocation;
            }
            set
            {
                OnClubLocationChanging(value);
                ReportPropertyChanging("ClubLocation");
                _ClubLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClubLocation");
                OnClubLocationChanged();
            }
        }
        private global::System.String _ClubLocation;
        partial void OnClubLocationChanging(global::System.String value);
        partial void OnClubLocationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyPlayer")]
        public EntityCollection<TableHockeyPlayer> TableHockeyPlayer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyPlayer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyPlayer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UHSSWEB_DEVModel", Name="TableHockeyContest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableHockeyContest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TableHockeyContest object.
        /// </summary>
        /// <param name="contestId">Initial value of the ContestId property.</param>
        /// <param name="contestName">Initial value of the ContestName property.</param>
        /// <param name="contestDateOpened">Initial value of the ContestDateOpened property.</param>
        /// <param name="isFinalGame">Initial value of the isFinalGame property.</param>
        /// <param name="isGoalDifferenceRanked">Initial value of the isGoalDifferenceRanked property.</param>
        /// <param name="numberOfRounds">Initial value of the numberOfRounds property.</param>
        /// <param name="pointsWinningGame">Initial value of the PointsWinningGame property.</param>
        /// <param name="pointsTiedGame">Initial value of the PointsTiedGame property.</param>
        /// <param name="pointsLostGame">Initial value of the PointsLostGame property.</param>
        /// <param name="gameLengthMinutes">Initial value of the GameLengthMinutes property.</param>
        public static TableHockeyContest CreateTableHockeyContest(global::System.Int32 contestId, global::System.String contestName, global::System.DateTime contestDateOpened, global::System.Boolean isFinalGame, global::System.Boolean isGoalDifferenceRanked, global::System.Int32 numberOfRounds, global::System.Int32 pointsWinningGame, global::System.Int32 pointsTiedGame, global::System.Int32 pointsLostGame, global::System.Int32 gameLengthMinutes)
        {
            TableHockeyContest tableHockeyContest = new TableHockeyContest();
            tableHockeyContest.ContestId = contestId;
            tableHockeyContest.ContestName = contestName;
            tableHockeyContest.ContestDateOpened = contestDateOpened;
            tableHockeyContest.isFinalGame = isFinalGame;
            tableHockeyContest.isGoalDifferenceRanked = isGoalDifferenceRanked;
            tableHockeyContest.numberOfRounds = numberOfRounds;
            tableHockeyContest.PointsWinningGame = pointsWinningGame;
            tableHockeyContest.PointsTiedGame = pointsTiedGame;
            tableHockeyContest.PointsLostGame = pointsLostGame;
            tableHockeyContest.GameLengthMinutes = gameLengthMinutes;
            return tableHockeyContest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContestId
        {
            get
            {
                return _ContestId;
            }
            set
            {
                if (_ContestId != value)
                {
                    OnContestIdChanging(value);
                    ReportPropertyChanging("ContestId");
                    _ContestId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContestId");
                    OnContestIdChanged();
                }
            }
        }
        private global::System.Int32 _ContestId;
        partial void OnContestIdChanging(global::System.Int32 value);
        partial void OnContestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContestName
        {
            get
            {
                return _ContestName;
            }
            set
            {
                OnContestNameChanging(value);
                ReportPropertyChanging("ContestName");
                _ContestName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContestName");
                OnContestNameChanged();
            }
        }
        private global::System.String _ContestName;
        partial void OnContestNameChanging(global::System.String value);
        partial void OnContestNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ContestDateOpened
        {
            get
            {
                return _ContestDateOpened;
            }
            set
            {
                OnContestDateOpenedChanging(value);
                ReportPropertyChanging("ContestDateOpened");
                _ContestDateOpened = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContestDateOpened");
                OnContestDateOpenedChanged();
            }
        }
        private global::System.DateTime _ContestDateOpened;
        partial void OnContestDateOpenedChanging(global::System.DateTime value);
        partial void OnContestDateOpenedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContestLocation
        {
            get
            {
                return _ContestLocation;
            }
            set
            {
                OnContestLocationChanging(value);
                ReportPropertyChanging("ContestLocation");
                _ContestLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContestLocation");
                OnContestLocationChanged();
            }
        }
        private global::System.String _ContestLocation;
        partial void OnContestLocationChanging(global::System.String value);
        partial void OnContestLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ContestDateClosed
        {
            get
            {
                return _ContestDateClosed;
            }
            set
            {
                OnContestDateClosedChanging(value);
                ReportPropertyChanging("ContestDateClosed");
                _ContestDateClosed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContestDateClosed");
                OnContestDateClosedChanged();
            }
        }
        private Nullable<global::System.DateTime> _ContestDateClosed;
        partial void OnContestDateClosedChanging(Nullable<global::System.DateTime> value);
        partial void OnContestDateClosedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContestDescription
        {
            get
            {
                return _ContestDescription;
            }
            set
            {
                OnContestDescriptionChanging(value);
                ReportPropertyChanging("ContestDescription");
                _ContestDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContestDescription");
                OnContestDescriptionChanged();
            }
        }
        private global::System.String _ContestDescription;
        partial void OnContestDescriptionChanging(global::System.String value);
        partial void OnContestDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ContestBinary
        {
            get
            {
                return StructuralObject.GetValidValue(_ContestBinary);
            }
            set
            {
                OnContestBinaryChanging(value);
                ReportPropertyChanging("ContestBinary");
                _ContestBinary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContestBinary");
                OnContestBinaryChanged();
            }
        }
        private global::System.Byte[] _ContestBinary;
        partial void OnContestBinaryChanging(global::System.Byte[] value);
        partial void OnContestBinaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isFinalGame
        {
            get
            {
                return _isFinalGame;
            }
            set
            {
                OnisFinalGameChanging(value);
                ReportPropertyChanging("isFinalGame");
                _isFinalGame = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isFinalGame");
                OnisFinalGameChanged();
            }
        }
        private global::System.Boolean _isFinalGame;
        partial void OnisFinalGameChanging(global::System.Boolean value);
        partial void OnisFinalGameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isGoalDifferenceRanked
        {
            get
            {
                return _isGoalDifferenceRanked;
            }
            set
            {
                OnisGoalDifferenceRankedChanging(value);
                ReportPropertyChanging("isGoalDifferenceRanked");
                _isGoalDifferenceRanked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isGoalDifferenceRanked");
                OnisGoalDifferenceRankedChanged();
            }
        }
        private global::System.Boolean _isGoalDifferenceRanked;
        partial void OnisGoalDifferenceRankedChanging(global::System.Boolean value);
        partial void OnisGoalDifferenceRankedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numberOfRounds
        {
            get
            {
                return _numberOfRounds;
            }
            set
            {
                OnnumberOfRoundsChanging(value);
                ReportPropertyChanging("numberOfRounds");
                _numberOfRounds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numberOfRounds");
                OnnumberOfRoundsChanged();
            }
        }
        private global::System.Int32 _numberOfRounds;
        partial void OnnumberOfRoundsChanging(global::System.Int32 value);
        partial void OnnumberOfRoundsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PointsWinningGame
        {
            get
            {
                return _PointsWinningGame;
            }
            set
            {
                OnPointsWinningGameChanging(value);
                ReportPropertyChanging("PointsWinningGame");
                _PointsWinningGame = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PointsWinningGame");
                OnPointsWinningGameChanged();
            }
        }
        private global::System.Int32 _PointsWinningGame;
        partial void OnPointsWinningGameChanging(global::System.Int32 value);
        partial void OnPointsWinningGameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PointsTiedGame
        {
            get
            {
                return _PointsTiedGame;
            }
            set
            {
                OnPointsTiedGameChanging(value);
                ReportPropertyChanging("PointsTiedGame");
                _PointsTiedGame = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PointsTiedGame");
                OnPointsTiedGameChanged();
            }
        }
        private global::System.Int32 _PointsTiedGame;
        partial void OnPointsTiedGameChanging(global::System.Int32 value);
        partial void OnPointsTiedGameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PointsLostGame
        {
            get
            {
                return _PointsLostGame;
            }
            set
            {
                OnPointsLostGameChanging(value);
                ReportPropertyChanging("PointsLostGame");
                _PointsLostGame = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PointsLostGame");
                OnPointsLostGameChanged();
            }
        }
        private global::System.Int32 _PointsLostGame;
        partial void OnPointsLostGameChanging(global::System.Int32 value);
        partial void OnPointsLostGameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameLengthMinutes
        {
            get
            {
                return _GameLengthMinutes;
            }
            set
            {
                OnGameLengthMinutesChanging(value);
                ReportPropertyChanging("GameLengthMinutes");
                _GameLengthMinutes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameLengthMinutes");
                OnGameLengthMinutesChanged();
            }
        }
        private global::System.Int32 _GameLengthMinutes;
        partial void OnGameLengthMinutesChanging(global::System.Int32 value);
        partial void OnGameLengthMinutesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumberOfPlayersToNextRound
        {
            get
            {
                return _NumberOfPlayersToNextRound;
            }
            set
            {
                OnNumberOfPlayersToNextRoundChanging(value);
                ReportPropertyChanging("NumberOfPlayersToNextRound");
                _NumberOfPlayersToNextRound = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfPlayersToNextRound");
                OnNumberOfPlayersToNextRoundChanged();
            }
        }
        private Nullable<global::System.Int32> _NumberOfPlayersToNextRound;
        partial void OnNumberOfPlayersToNextRoundChanging(Nullable<global::System.Int32> value);
        partial void OnNumberOfPlayersToNextRoundChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyContest", "TableHockeyGame")]
        public EntityCollection<TableHockeyGame> TableHockeyGame
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableHockeyGame>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyContest", "TableHockeyGame");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableHockeyGame>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyContest", "TableHockeyGame", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UHSSWEB_DEVModel", Name="TableHockeyGame")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableHockeyGame : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TableHockeyGame object.
        /// </summary>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="homePlayerId">Initial value of the HomePlayerId property.</param>
        /// <param name="awayPlayerId">Initial value of the AwayPlayerId property.</param>
        /// <param name="gameStartDate">Initial value of the GameStartDate property.</param>
        /// <param name="isFinalGame">Initial value of the isFinalGame property.</param>
        /// <param name="hasSuddenDeath">Initial value of the hasSuddenDeath property.</param>
        /// <param name="contestId">Initial value of the ContestId property.</param>
        public static TableHockeyGame CreateTableHockeyGame(global::System.Int32 gameId, global::System.Int32 homePlayerId, global::System.Int32 awayPlayerId, global::System.DateTime gameStartDate, global::System.Boolean isFinalGame, global::System.Boolean hasSuddenDeath, global::System.Int32 contestId)
        {
            TableHockeyGame tableHockeyGame = new TableHockeyGame();
            tableHockeyGame.GameId = gameId;
            tableHockeyGame.HomePlayerId = homePlayerId;
            tableHockeyGame.AwayPlayerId = awayPlayerId;
            tableHockeyGame.GameStartDate = gameStartDate;
            tableHockeyGame.isFinalGame = isFinalGame;
            tableHockeyGame.hasSuddenDeath = hasSuddenDeath;
            tableHockeyGame.ContestId = contestId;
            return tableHockeyGame;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                if (_GameId != value)
                {
                    OnGameIdChanging(value);
                    ReportPropertyChanging("GameId");
                    _GameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameId");
                    OnGameIdChanged();
                }
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HomePlayerId
        {
            get
            {
                return _HomePlayerId;
            }
            set
            {
                OnHomePlayerIdChanging(value);
                ReportPropertyChanging("HomePlayerId");
                _HomePlayerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HomePlayerId");
                OnHomePlayerIdChanged();
            }
        }
        private global::System.Int32 _HomePlayerId;
        partial void OnHomePlayerIdChanging(global::System.Int32 value);
        partial void OnHomePlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AwayPlayerId
        {
            get
            {
                return _AwayPlayerId;
            }
            set
            {
                OnAwayPlayerIdChanging(value);
                ReportPropertyChanging("AwayPlayerId");
                _AwayPlayerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AwayPlayerId");
                OnAwayPlayerIdChanged();
            }
        }
        private global::System.Int32 _AwayPlayerId;
        partial void OnAwayPlayerIdChanging(global::System.Int32 value);
        partial void OnAwayPlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HomePlayerScore
        {
            get
            {
                return _HomePlayerScore;
            }
            set
            {
                OnHomePlayerScoreChanging(value);
                ReportPropertyChanging("HomePlayerScore");
                _HomePlayerScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HomePlayerScore");
                OnHomePlayerScoreChanged();
            }
        }
        private Nullable<global::System.Int32> _HomePlayerScore;
        partial void OnHomePlayerScoreChanging(Nullable<global::System.Int32> value);
        partial void OnHomePlayerScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AwayPlayerScore
        {
            get
            {
                return _AwayPlayerScore;
            }
            set
            {
                OnAwayPlayerScoreChanging(value);
                ReportPropertyChanging("AwayPlayerScore");
                _AwayPlayerScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AwayPlayerScore");
                OnAwayPlayerScoreChanged();
            }
        }
        private Nullable<global::System.Int32> _AwayPlayerScore;
        partial void OnAwayPlayerScoreChanging(Nullable<global::System.Int32> value);
        partial void OnAwayPlayerScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime GameStartDate
        {
            get
            {
                return _GameStartDate;
            }
            set
            {
                OnGameStartDateChanging(value);
                ReportPropertyChanging("GameStartDate");
                _GameStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameStartDate");
                OnGameStartDateChanged();
            }
        }
        private global::System.DateTime _GameStartDate;
        partial void OnGameStartDateChanging(global::System.DateTime value);
        partial void OnGameStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GameClosedDate
        {
            get
            {
                return _GameClosedDate;
            }
            set
            {
                OnGameClosedDateChanging(value);
                ReportPropertyChanging("GameClosedDate");
                _GameClosedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameClosedDate");
                OnGameClosedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GameClosedDate;
        partial void OnGameClosedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGameClosedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isFinalGame
        {
            get
            {
                return _isFinalGame;
            }
            set
            {
                OnisFinalGameChanging(value);
                ReportPropertyChanging("isFinalGame");
                _isFinalGame = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isFinalGame");
                OnisFinalGameChanged();
            }
        }
        private global::System.Boolean _isFinalGame;
        partial void OnisFinalGameChanging(global::System.Boolean value);
        partial void OnisFinalGameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean hasSuddenDeath
        {
            get
            {
                return _hasSuddenDeath;
            }
            set
            {
                OnhasSuddenDeathChanging(value);
                ReportPropertyChanging("hasSuddenDeath");
                _hasSuddenDeath = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasSuddenDeath");
                OnhasSuddenDeathChanged();
            }
        }
        private global::System.Boolean _hasSuddenDeath;
        partial void OnhasSuddenDeathChanging(global::System.Boolean value);
        partial void OnhasSuddenDeathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContestId
        {
            get
            {
                return _ContestId;
            }
            set
            {
                OnContestIdChanging(value);
                ReportPropertyChanging("ContestId");
                _ContestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContestId");
                OnContestIdChanged();
            }
        }
        private global::System.Int32 _ContestId;
        partial void OnContestIdChanging(global::System.Int32 value);
        partial void OnContestIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyContest", "TableHockeyContest")]
        public TableHockeyContest TableHockeyContest
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyContest>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyContest", "TableHockeyContest").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyContest>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyContest", "TableHockeyContest").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TableHockeyContest> TableHockeyContestReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyContest>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyContest", "TableHockeyContest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TableHockeyContest>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyContest", "TableHockeyContest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyPlayer")]
        public TableHockeyPlayer TableHockeyPlayer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyPlayer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyPlayer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TableHockeyPlayer> TableHockeyPlayerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyPlayer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyPlayer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyPlayer")]
        public TableHockeyPlayer TableHockeyPlayer1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyPlayer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyPlayer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TableHockeyPlayer> TableHockeyPlayer1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyPlayer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TableHockeyPlayer>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyPlayer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UHSSWEB_DEVModel", Name="TableHockeyPlayer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableHockeyPlayer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TableHockeyPlayer object.
        /// </summary>
        /// <param name="playerId">Initial value of the PlayerId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="clubId">Initial value of the ClubId property.</param>
        public static TableHockeyPlayer CreateTableHockeyPlayer(global::System.Int32 playerId, global::System.String firstName, global::System.String lastName, global::System.Int32 clubId)
        {
            TableHockeyPlayer tableHockeyPlayer = new TableHockeyPlayer();
            tableHockeyPlayer.PlayerId = playerId;
            tableHockeyPlayer.FirstName = firstName;
            tableHockeyPlayer.LastName = lastName;
            tableHockeyPlayer.ClubId = clubId;
            return tableHockeyPlayer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerId
        {
            get
            {
                return _PlayerId;
            }
            set
            {
                if (_PlayerId != value)
                {
                    OnPlayerIdChanging(value);
                    ReportPropertyChanging("PlayerId");
                    _PlayerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlayerId");
                    OnPlayerIdChanged();
                }
            }
        }
        private global::System.Int32 _PlayerId;
        partial void OnPlayerIdChanging(global::System.Int32 value);
        partial void OnPlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClubId
        {
            get
            {
                return _ClubId;
            }
            set
            {
                OnClubIdChanging(value);
                ReportPropertyChanging("ClubId");
                _ClubId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClubId");
                OnClubIdChanged();
            }
        }
        private global::System.Int32 _ClubId;
        partial void OnClubIdChanging(global::System.Int32 value);
        partial void OnClubIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyClub")]
        public TableHockeyClub TableHockeyClub
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyClub>("UHSSWEB_DEVModel.FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyClub").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyClub>("UHSSWEB_DEVModel.FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyClub").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TableHockeyClub> TableHockeyClubReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableHockeyClub>("UHSSWEB_DEVModel.FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyClub");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TableHockeyClub>("UHSSWEB_DEVModel.FK_TableHockeyPlayer_TableHockeyClub", "TableHockeyClub", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyGame")]
        public EntityCollection<TableHockeyGame> TableHockeyGame
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableHockeyGame>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyGame");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableHockeyGame>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer", "TableHockeyGame", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UHSSWEB_DEVModel", "FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyGame")]
        public EntityCollection<TableHockeyGame> TableHockeyGame1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableHockeyGame>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyGame");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableHockeyGame>("UHSSWEB_DEVModel.FK_TableHockeyGame_TableHockeyPlayer1", "TableHockeyGame", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
